name: dicast
channels:
  - conda-forge
  - bioconda
dependencies:
  - python=3.10
  - numpy
  - pandas
  - xgboost>=1.7,<3
  - pysam
  - pyBigWig
  - bioframe
  - vcfpy
  - matplotlib
  - pyyaml
  - tqdm
  - joblib
  - packaging
  - networkx
