variant:
  sv_len: 1
reference:
  rep_LINE: 1
  rep_SINE: 1
  rep_LTR: 1
  rep_DNA: 1
  rep_Simple_repeat: 1
  rep_Satellite: 1
  rep_Low_complexity: 1
  rep_Retroposon: 1
  rep_snRNA: 1
  rep_tRNA: 1
  rep_srpRNA: 1
  rep_rRNA: 1
  rep_RC: 1
  rep_scRNA: 1
  rep_RNA: 1
  rep_VNTR: 1
  rep_STR: 1
  cpg_islands: 1
  centromeres: 1
  asmb_gaps: 1
  alt_haps: 1
  GC_content_left: 1
  GC_content_right: 1
alignment:
  ill_cov_mean: 1
  ill_cov_std: 1
  ill_isize_mean: 1
  ill_isize_std: 1
  ill_mapq_mean: 1
  ill_mapq_std: 1
  ill_clipreads: 1
  ill_splitreads: 1
  ill_disco_ff: 1 
  ill_disco_rr: 1  
  ill_disco_rf: 1  
  ill_disco_tx: 1
alignment_body:
  ill_cov_mean: 1
  ill_cov_std: 1
alignment_conn:
  ill_splitreads: 1
  ill_disco_ff: 1
  ill_disco_rr: 1
  ill_disco_rf: 1
