variant:
  sv_len: 0
reference:
  rep_LINE: 0
  rep_SINE: 0
  rep_LTR: 0
  rep_DNA: 0
  rep_Simple_repeat: 0
  rep_Satellite: 0
  rep_Low_complexity: 0
  rep_Retroposon: 0
  rep_snRNA: 0
  rep_tRNA: 0
  rep_srpRNA: 0
  rep_rRNA: 0
  rep_RC: 0
  rep_scRNA: 0
  rep_RNA: 0
  rep_VNTR: 0
  rep_STR: 0
  cpg_islands: 0
  centromeres: 0
  asmb_gaps: 0
  alt_haps: 0
  GC_content_left: 1
  GC_content_right: 1
alignment:
  ill_cov_mean: 1
  ill_cov_std: 1
  ill_isize_mean: 0
  ill_isize_std: 0
  ill_mapq_mean: 0
  ill_mapq_std: 0
  ill_clipreads: 0
  ill_splitreads: 0
  ill_disco_ff: 0
  ill_disco_rr: 0  
  ill_disco_rf: 0  
  ill_disco_tx: 0
alignment_body:
  ill_cov_mean: 1
  ill_cov_std: 1
alignment_conn:
  ill_splitreads: 0
  ill_disco_ff: 0
  ill_disco_rr: 0
  ill_disco_rf: 0
